// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const box: string
export const bottom: string
export const quote: string
export const image: string
export const name: string
export const description: string
