// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const content: string
export const icon: string
export const contactButton: string
export const linkArrow: string
export const paragraph: string
