// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const themedText: string
export const muted: string
export const body: string
export const detail: string
export const lead: string
