// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const h1: string;
export const h2: string;
export const h3: string;
export const h4: string;
export const h5: string;
export const h6: string;
