// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const staticStorageUrl: string
export const particlesBg: string
export const particlesContainer: string
export const redParticle: string
export const formCard: string
export const margin: string
export const separator: string
export const muted: string
