// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const componentHighlighter: string;
export const active: string;
export const highlighting: string;
export const tooltip: string;
export const border: string;
export const link: string;
