// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const communitySection: string
export const title: string
export const tweets: string
export const tweet: string
export const cta: string
export const text: string
export const links: string
