// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const staticStorageUrl: string
export const supportCirclesBg: string
export const supportPageStyles: string
export const foldMargin: string
export const marginBottom150: string
export const supportCta: string
