// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const grid: string
export const paragraph: string
export const content: string
export const supportCard: string
export const cardIcon: string
export const cardTitle: string
