// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const staticStorageUrl: string
export const enterpriseOffering: string
export const supportCirclesBg: string
export const gradient00: string
export const gradient01: string
export const gradient02: string
export const foldMargin: string
export const foldMarginPlus: string
export const circlesMargin: string
export const curveMargin: string
export const curve: string
export const curveCloud: string
export const curveWhite: string
export const expertSupport: string
export const paddingTop30: string
export const paddingTop130: string
export const margin160: string
