// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const snippetWrapper: string
export const copyIcon: string
export const codeSnippet: string
export const copy: string
