// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const topSection: string
export const top: string
export const title: string
export const paragraph: string
export const image: string
export const spacer: string
export const buttons: string
export const button: string
