// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const mainGrid: string
export const image: string
export const content: string
export const mainParagraph: string
export const link: string
export const channelButton: string
export const slack: string
export const email: string
export const emailIcon: string
export const github: string
