// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const mainGrid: string
export const spacer: string
export const headline: string
export const paragraph: string
export const buttons: string
export const icons: string
