// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const staticStorageUrl: string
export const purpleBackground: string
export const hotpinkBackground: string
export const uEllipse: string
export const greyBackground: string
export const greyBgPadding: string
export const foldMargin: string
export const landingSection: string
export const separator: string
export const margin30: string
export const margin100: string
export const margin130: string
export const margin180: string
