// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const staticStorageUrl: string
export const content: string
export const corpoBg: string
export const corposphere: string
export const bulletList: string
export const title: string
export const bullet: string
