// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const mainGrid: string
export const content: string
export const image: string
export const buttons: string
export const link: string
export const button: string
export const spacer: string
export const paragraph: string
