// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const poweringEnterprise: string
export const crunchTheNumbers: string
export const separator: string
export const emphasized: string
export const xtraEmpthasized: string
