// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const centerColumn: string
export const wideColumn: string
export const textColumn: string
