module.exports = {
  siteMetadata: {
    title: `home`,
    description: `This is a gatsby application created by Nx.`
  },
  plugins: [
    "gatsby-plugin-sass",

    {
      resolve: "gatsby-plugin-svgr",
      options: {
        svgo: false,
        ref: true
      }
    },
    `gatsby-plugin-react-helmet`,
    {
      resolve: `gatsby-source-filesystem`,
      options: {
        name: `images`,
        path: `${__dirname}/src/images`
      }
    },
    `gatsby-plugin-image`,
    `gatsby-transformer-sharp`,
    {
      resolve: require.resolve(`@nrwl/gatsby/plugins/nx-gatsby-ext-plugin`),
      options: {
        path: __dirname
      }
    },
    `gatsby-plugin-sharp`,
    {
      resolve: `gatsby-plugin-manifest`,
      options: {
        name: `home`,
        short_name: `starter`,
        start_url: `/`,
        background_color: `#663399`,
        theme_color: `#663399`,
        display: `minimal-ui`,
        icon: `src/images/logo.svg`
      }
    },
    {
      resolve: "gatsby-plugin-dts-css-modules",
      options: {
        /** @default {true} */
        // namedExport: false,

        /** @default {'// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!'} */
        // banner: '// My own banner',

        // customTypings: (classes) => classes.map((className) => `export const ${className}: string;`).join('\n'),

        dropEmptyFile: true
      }
    },
    {
      resolve: require.resolve("../../libs/gatsby-plugin-emotion")
    },
    {
      resolve: require.resolve("../../libs/gatsby-plugin-top-layout")
    }
  ]
}
