// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const headingFontSize: string
export const textFontSize: string
export const spacing: string
