// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const iconLine: string
export const github: string
export const slack: string
export const logo: string
