// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const contactForm: string
export const grow: string
export const error: string
export const field: string
export const margin: string
