// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const bedrock: string
export const base: string
export const layer: string
export const crust: string
export const topping: string
export const dent: string
