// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const subtitle: string
export const mainImage: string
export const benefitsGrid: string
export const benefit: string
