// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const integrationBadges: string
export const logos: string
export const conveyerBelt: string
