// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const xxs: string;
export const xs: string;
export const sm: string;
export const md: string;
export const lg: string;
export const xl: string;
export const xxl: string;
