// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const margin30: string
export const margin50: string
export const margin80: string
export const margin130: string
export const margin180: string
