// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const staticStorageUrl: string
export const paragraph: string
export const particlesBg: string
export const grid: string
export const card: string
export const subtitle: string
export const bullets: string
