// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const duoComponentBubble: string;
export const scopeBubble: string;
export const scopeName: string;
export const componentName: string;
export const separator: string;
export const link: string;
export const versionPrefix: string;
export const version: string;
export const fullName: string;
