// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const title: string
export const preventOverflow: string
export const mainContent: string
export const container: string
export const card: string
export const timestamp: string
export const chatHead01: string
export const chatHeads: string
