// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const sharp: string
export const normal: string
export const small: string
export const medium: string
export const circle: string
