export const duoComponentBubble: string
export const scopeBubble: string
export const scopeName: string
export const componentName: string
export const fullName: string
export const version: string
export const separator: string
export const link: string
export const versionPrefix: string
