// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const scrollPreventer: string
export const customGrid: string
export const imgContainer: string
export const list: string
