// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const primary: string
export const complementary: string
export const impulsive: string
export const hungry: string
export const success: string
export const process: string
export const emphasized: string
export const neutral: string
