export const primary: string
export const complementary: string
export const complementary: string
export const hungry: string
export const success: string
export const process: string
export const emphasized: string
export const neutral: string
export const impulsive: string
