// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const twitterCard: string
export const avatar: string
export const title: string
export const icon: string
export const text: string
